server:
  port: 9090
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.reactive.ReactiveSecurityAutoConfiguration
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/wordly
    username: admin
    password: admin
    pool:
      max-size: 10
      max-create-connection-time: 10s
---
spring:
  config:
    activate:
      on-profile: sandbox
  r2dbc:
    url: ${MARIADB_URL}
    username: ${MARIADB_USER}
    password: ${MARIADB_PASSWORD}
    pool:
      max-size: 10
      max-create-connection-time: 10s
